USE [master]
GO

/****** Object:  Database [Hospital_Py]    Script Date: 11/14/2017 7:21:01 PM ******/
CREATE DATABASE [Hospital_Py]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hospital_Py', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Hospital_Py.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hospital_Py_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Hospital_Py_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hospital_Py].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hospital_Py] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hospital_Py] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hospital_Py] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hospital_Py] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hospital_Py] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hospital_Py] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hospital_Py] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hospital_Py] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hospital_Py] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hospital_Py] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hospital_Py] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hospital_Py] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hospital_Py] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hospital_Py] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hospital_Py] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Hospital_Py] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hospital_Py] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hospital_Py] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hospital_Py] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hospital_Py] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hospital_Py] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hospital_Py] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hospital_Py] SET RECOVERY FULL 
GO

ALTER DATABASE [Hospital_Py] SET  MULTI_USER 
GO

ALTER DATABASE [Hospital_Py] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hospital_Py] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hospital_Py] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hospital_Py] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hospital_Py] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hospital_Py] SET QUERY_STORE = OFF
GO

USE [Hospital_Py]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Hospital_Py] SET  READ_WRITE 
GO


